export const ADMIN = 'ADMIN'
export const PERSON = 'PERSON'
export const ERROR_STATE = 'ERROR_STATE'
export const IS_AUTH = 'IS_AUTH'
export const CONTEXT = 'CONTEXT'
export const SIDEBARS= 'SIDEBARS'
export const HEADER_MESSAGE = 'HEADER_MESSAGE'
